services:
  database:
    container_name: foodfy-hono-bun
    image: postgres:17.4-alpine3.21
    env_file:
      - .env.development
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U docker -d foodfy-hono-bun'"]
      interval: 10s
      timeout: 5s
      retries: 5
