name: Test

on: pull_request

env:
  bun: 1.2.9

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    services:
      database:
        options: --name foodfy-hono-bun-postgres-dev
        image: postgres:17.4-alpine3.21
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: foodfy-hono-bun
          DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
      mailhog:
        image: mailhog/mailhog:v1.0.1
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.bun }}

      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ env.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.bun }}-bun-

      - name: install dependencies
        run: bun install

      - name: run tests
        run: bun run test
